TAX-3.8 Zadanie: bankomat
tglogowski/tomasz_glogowski-kodilla_tester pull request #23
Opened 2023-01-09 23:40 UTC by tglogowski

2023-01-10 20:29 UTC, mps4dev requested changes

2023-01-10 20:29 UTC, mps4dev commented on kodilla-basic-tests/src/main/java/com/kodilla/bank/homework/Bank.java
> +    private static final int NUMBER_OF_CASH_MACHINES =2;
Dlaczego 2?

2023-01-10 20:29 UTC, mps4dev commented on kodilla-basic-tests/src/main/java/com/kodilla/bank/homework/Bank.java
> +        for(int i = 0; i < NUMBER_OF_CASH_MACHINES ; i++) {
Czemu? this.cashMachines.length

2023-01-10 21:58 UTC, tglogowski commented on kodilla-basic-tests/src/main/java/com/kodilla/bank/homework/Bank.java
> +    private static final int NUMBER_OF_CASH_MACHINES =2;
faktycznie, nie jest potrzebna ta stała bo w klasie testów można ustalić ilość bankomatów. Przekombinowałem :)

2023-01-11 15:50 UTC, mps4dev requested changes

2023-01-11 15:50 UTC, mps4dev commented on kodilla-basic-tests/src/main/java/com/kodilla/bank/homework/Bank.java
> +        int sum =0;
spacja po znaku =

2023-01-11 15:50 UTC, mps4dev commented on kodilla-basic-tests/src/main/java/com/kodilla/bank/homework/Bank.java
> +            tempTab = cashMachines[i].getTransactions();
Proponuje, aby CacheMachine mialo metode, ktora odpowie na pytanie ile bylo wyplat

2023-01-11 15:50 UTC, mps4dev commented on kodilla-basic-tests/src/main/java/com/kodilla/bank/homework/Bank.java
> +            tempTab = cashMachines[i].getTransactions();
jak wyzej

2023-01-11 15:50 UTC, mps4dev commented on kodilla-basic-tests/src/main/java/com/kodilla/bank/homework/Bank.java
> +            for (int j = 0; j < tempTab.length; j++) {
For w for wyglada nieladnie - jak wyzej (CacheMachine moze miec metode getTotalPayouts i getTotalPayments)

2023-01-11 15:50 UTC, mps4dev commented on kodilla-basic-tests/src/main/java/com/kodilla/bank/homework/Bank.java
> +        int sum = 0;
double sum = 0 i nie trzeba potem castowac (castowanie jest nieladne)

2023-01-11 15:50 UTC, mps4dev commented on kodilla-basic-tests/src/main/java/com/kodilla/bank/homework/CashMachine.java
> +    public void addTransaction(int cash) {
proponuje parametr nazwac transaction a nie cash

2023-01-11 15:50 UTC, mps4dev commented on kodilla-basic-tests/src/main/java/com/kodilla/bank/homework/CashMachine.java
> +    public int getCountOfCashMachines() {
Czemu CashMachine ma wiedziec ile jest cashMachines???

2023-01-11 22:19 UTC, merged