Tax 2.5
tglogowski/tomasz_glogowski-kodilla_tester pull request #5
Opened 2022-12-28 09:33 UTC by tglogowski

2022-12-29 16:27 UTC, mps4dev requested changes
Utworz klase, ktora bedzie miala prywatne pola min oraz max, dodaj gettery. Zrob rowniez metide void process(), ktorarobi to co w zadaniu i za kazdym razem aktualizuje pola min i max.

2022-12-29 18:51 UTC, tglogowski commented
Poprawiłem. Utworzyłem nową klasę  "RndMinMax" a w niej 2 gettery i metodę process().

2022-12-30 18:54 UTC, mps4dev requested changes

2022-12-30 18:54 UTC, mps4dev commented on kodilla-intro/src/main/java/User.java
> +        if (this.size > 0) {
raczej najpierw sprawdzamy warunek, a potem liczymy :) Gdy size == 0 to bez sensu wykonujesz operacje z linii 22 - 31 :)

2022-12-30 18:54 UTC, mps4dev commented on kodilla-intro/src/main/java/User.java
> +    private int[] age;
Jeden user ma tablice imion i tablice lat?

2022-12-30 18:54 UTC, mps4dev commented on kodilla-intro/src/main/java/User.java
> +        user.userList(user.calcAveAge());
Zobacz, wywolujesz metode z obiektu user i podajesz jako argument znowu wywolanie metody z obiektu user (czyli user sam moglby wszystko se policzyc). 
Ty masz w zadaniu tutaj zrobic w metodzie main tablice User'ów, policzyc srednia, wypisac. Obiekt User odpowiada za jednego Usera raczej. Mozesz wprowadzic klase UserProcessor, ktora dostanie w konstruktorze tablice User'ów i wtedy obliczy (w konstruktorze) sredni wiek.

2022-12-30 18:54 UTC, mps4dev commented on kodilla-intro/src/main/java/RndMinMax.java
> +            drawCount++;
zamiast tego drawCount mozna poprostu minMumber na poczatku ustawic na 31 a maxNumber na -1.

2023-01-01 14:43 UTC, mps4dev requested changes

2023-01-01 14:43 UTC, mps4dev commented on kodilla-intro/src/main/java/RndMinMax.java
> +        Random rnd = new Random();
ile obiektow typu Random utworzysz w metodzie process? Czym te obiekty beda sie od siebie roznic?

2023-01-01 14:43 UTC, mps4dev commented on kodilla-intro/src/main/java/User.java
> +    public static void main(String[] args) {
proponuje metode main umiescic w innej klasie, no. UserApplication

2023-01-01 14:43 UTC, mps4dev commented on kodilla-intro/src/main/java/User.java
> +        if (user.length > 0) {
Napisz metode liczaca sredni wiek

2023-01-02 17:47 UTC, mps4dev requested changes
Jeden user nie moze nic wiedziec o innych userach

2023-01-03 18:54 UTC, mps4dev requested changes
Juz jest duzo lepiej

2023-01-03 18:54 UTC, mps4dev commented on kodilla-intro/src/main/java/RndMinMax.java
> +    Random rnd = new Random();
moze byc: private static Random random = new Random();

2023-01-03 18:54 UTC, mps4dev commented on kodilla-intro/src/main/java/RndMinMax.java
> +        int sumMax = 5000;
zbedna ta zmienna, mozna zrobic stala w klasie:
private static final int MAX_SUM = 5000;

2023-01-03 18:54 UTC, mps4dev commented on kodilla-intro/src/main/java/UserApplication.java
> +    double aveAge;
to sa teraz pola w klasie UserApplication - po co? To moga byc zmienne (czyli zadeklarowane w metodzie)

2023-01-03 18:54 UTC, mps4dev commented on kodilla-intro/src/main/java/UserApplication.java
> +    private void addUsers(){
initUsers (nic tu nie dodajesz)

2023-01-04 19:34 UTC, mps4dev approved these changes

2023-01-04 19:35 UTC, merged