Tax 2.6 Refaktoryzacja kodu
tglogowski/tomasz_glogowski-kodilla_tester pull request #6
Opened 2022-12-28 09:46 UTC by tglogowski

2022-12-29 16:25 UTC, mps4dev requested changes

2022-12-29 16:25 UTC, mps4dev commented on kodilla-intro/src/main/java/Human.java
> +    double age1;
Czemu age1?  
Pola zrob private

2022-12-29 19:31 UTC, tglogowski commented on kodilla-intro/src/main/java/Human.java
> +    double age1;
Poprawione. Nie wiem czemu dodałem te indeksy - jakaś maniera mi została z dawnych lat :)

2023-01-01 14:45 UTC, mps4dev approved these changes

2023-01-04 19:42 UTC, merged